using MailKit.Net.Smtp;
using MailKit.Security;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MimeKit.Text;

namespace Project_C.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class EmailController : ControllerBase
    {
        [HttpPost]
        public IActionResult SendEmail(string body) {
            var email = new MimeMessage();
            // email and password are credentials generated by ethereal.email
            var emailAddress = "alessandro7@ethereal.email";
            email.From.Add(MailboxAddress.Parse(emailAddress));
            email.To.Add(MailboxAddress.Parse(emailAddress));
            email.Subject = "Test";
            email.Body = new TextPart(TextFormat.Html) { Text = body};

            using var smtp = new SmtpClient();
            smtp.Connect("smtp.ethereal.email", 587, SecureSocketOptions.StartTls);
            smtp.Authenticate(emailAddress, "GeVuPxMzy6cbu3swWu"); // email and password
            smtp.Send(email);
            smtp.Disconnect(true);

            return Ok();
        }
    }
}